// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxsukvtjtpppbqsxcbqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4c3VrdnRqdHBwcGJxc3hjYnFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTkzNDksImV4cCI6MjA2OTYzNTM0OX0.NK3T2hDZn3_ZECv8iyTThYS7qNdUWihxBot4RABVOV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});